# Generated by Django 5.2.14 on 2026-06-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0002_helprequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helprequest",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("resolved", "Resolved")],
                db_index=True,
                default="open",
                max_length=20,
            ),
        ),
    ]
