# Generated by Django 5.1.15 on 2026-06-14 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_lesson_learning_objectives_tips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
