# Generated by Django 5.2.14 on 2026-06-02 09:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="verification_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
